logging:
  level:
    software.hoegg.okcjug: INFO
device:
  location:
    latitude: 35.46679
    longitude: -97.5343547
    woe-id: 12789622
api:
  weather-unlocked:
    app-id: 12345678
    key: aaaaaaaaaaaaaaaaaa
  yahoo:
    app-id: 12345678
    client-id: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb--
    client-secret: 22222222222222222222222222222222
weather:
  ribbon:
    #listOfServers: http://api.weatherunlocked.com
    listOfServers: http://1.2.3.4
yahoo:
  ribbon:
    listOfServers: https://weather-ydn-yql.media.yahoo.com
ribbon:
  eureka:
    enabled: false
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  ReadTimeout: 2000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000